---
- hosts: all
  become: yes

  pre_tasks:
    - name: "Update apt repo and cache on Ubuntu box"
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: "Upgrade all packages on servers"
      apt:
        upgrade: dist
        force_apt_get: yes
  tasks:
    - name: Install Nginx
      apt:
            name: nginx
            state: latest
      notify:
        - Start Nginx

    - name: Copy nginx config
      # Only requirement is that the dst path exists in the default system python path
      copy: src=nginx.conf dest=/etc/nginx/nginx.conf
      notify:
        - Restart Nginx

    - name: Allow Nginx Full in firewall
      shell: ufw allow 'Nginx Full'

    - name: Install python3-pip and python3-venv
      apt:
          name: "{{ item }}"
          state: latest
      with_items:
        - python3-pip
        - python3-venv

    - name: Install nodejs
      apt:
          name: nodejs
          state: latest

    - name: Install certbot and python3-certbot-nginx
      apt:
          name: "{{ item }}"
          state: latest
      with_items:
        - certbot
        - python3-certbot-nginx

  handlers:
      - name: Start Nginx
        service:
            name: nginx
            state: started

      - name: Restart Nginx
        service:
            name: nginx
            state: restarted